#!/bin/bash
#SBATCH -N 1
#SBATCH -c 28
#SBATCH -p cpu
#SBATCH -t 01-00:00:00
#SBATCH --mem=32g
#SBATCH --qos=short
#SBATCH --job-name=acp_test
#SBATCH --mail-type=ALL
#SBATCH --mail-user kqcr86@durham.ac.uk

eval "$('/home2/kqcr86/anaconda3/bin/conda' 'shell.bash' 'hook' 2> /dev/null)"
conda activate py39
python ml_script1.py 